config/routes.rb
HackerNewsRails::Application.routes.draw do
  root :to => 'posts#index'
  
  resources :sessions, only: [:create, :new, :destroy]
  resources :users, only: [:create, :new, :destroy, :show]
  resources :posts do
    resources :comments, only: [:create, :new, :destroy]
  end

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  belongs_to :author, class_name: "User"

  validates :text, presence: true

  attr_accessible :text, :post_id, :author_id
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  attr_accessible :title, :url, :post_id, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password_digest, :password_confirmation, :password
  has_many :posts

  has_many :comments_received, through: :posts, source: :comments
  
  has_many :comments_written, class_name: "Comment"

  validates :email, presence: true

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    p "X"*100
    p params[:comment]
    @comment = @post.comments.create(params[:comment])
    redirect_to @post
  end

  def new
    @post = Post.find(params[:post_id])
  end


  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to user_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def create
    @post = Post.new(params[:post])
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    user = User.find_by_email(params[:user][:email])
    @user = user.authenticate(params[:user][:password])
    if @user
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      redirect_to posts_path
    end
  end

  def destroy
    session.clear
    redirect_to posts_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render 'new'
    end
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end

  def show
    @user = User.find(session[:user_id])
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/views/comments/new.html.haml
= form_for ([@post, @post.comments.build]) do |f|

  %p
    = f.label :text
    = f.text_field :text
  %p
    = f.hidden_field :author_id, value: current_user.id  
  %p
    = f.submit 

app/views/layouts/application.html.haml
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "App_Name"
    %meta{:content => content_for?(:description) ? yield(:description) : "App_Name", :name => "description"}
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags
    / = yield(:head)
  %body
    %nav 
      %ul
        %li
          = link_to "HOME", posts_path
        -if current_user
          %li
            = link_to current_user.email, user_path(current_user.id)
          %li
            = link_to "Logout", session_path(current_user), method: :delete
        -else 
          %li
            = link_to "Sign Up", new_user_path
          %li
            = link_to "Login", new_session_path
          %hr 
        
    #container.container

      #main{:role => "main"}
        = yield
      %footer

app/views/layouts/navigation.html.haml
%section
    %h1 Sign Up
    -form_for @user do |f|
        %p
            = f.label :email
            %br
            = f.text_field :email
        %p
            = f.label :password
            %br
            = f.text_field :password
        %p.button
            = f.submit
    -

app/views/posts/edit.html.haml
= form_for @post, url: post_path(@post.id) do |f|

  %p
    = f.label :title
    = f.text_field :title
  %p 
    = f.label :url
    = f.text_field :url
  %p
    = f.submit 

app/views/posts/index.html.haml
%section.home 
  %ol.posts
    - @posts.each do |post| 
      %ul
        %li
          = link_to post.title, post_path(post.id) 
        %hr

app/views/posts/new.html.haml
= form_for @post do |f|
  %p
    = f.label :title
    = f.text_field :title
  %p 
    = f.label :url
    = f.text_field :url
  %p
    = f.submit 

app/views/posts/show.html.haml
%section.post 
  %h1= @post.title 
  %h4= @post.url 
  %p= link_to "Create Comment", new_post_comment_path(post_id: @post.id)
  %ul
  - @comments.each do |comment| 
    %li 
      %h4=comment.author.email
      %p= comment.text 

 

app/views/users/new.html.haml
= form_for @user do |f|
  %p
    = f.label :email
    = f.text_field :email
  %p 
    = f.label :password
    = f.text_field :password
  %p
    = f.submit 

app/views/users/show.html.haml
%section.user
  %h4
    = link_to "Create Post", new_post_path 
  %h1
    = current_user.email
    = current_user.posts.count
  %ul 
  - current_user.posts.each do |post|
    %li
      %h2= post.title
      %ul
        %li= link_to "Edit", edit_post_path(post.id)
        %li= link_to "Delete", post_path(post.id), method: :delete
      %ul 
      %h4
        = "Comments"
        = post.comments.count
      - post.comments.each do |comment|
        %li
          %p= comment.text
      %hr
      %hr